version: "3.8"

services:
  # Laravel PHP App
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./logs:/var/www/html/storage/logs
    ports:
      - "8000:8000"  # for artisan serve (dev use only)
    mem_limit: 512m
    cpus: 0.5
    depends_on:
      - db
    networks:
      - app-network

  # NGINX Web Server
  webserver:
    image: nginx:alpine
    container_name: week_4_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html:ro                          # ✅ read-only
      - ./nginx/conf.d:/etc/nginx/conf.d:ro          # ✅ read-only
    depends_on:
      - app
    networks:
      - app-network
    read_only: true                                  # ✅ secure nginx container

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: week_4_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: week_4
      POSTGRES_USER: permin
      POSTGRES_PASSWORD: 4488
    volumes:
      - pgdata:/var/lib/postgresql/data
    mem_limit: 512m
    cpus: 0.5
    networks:
      - app-network

  # pgAdmin GUI
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
