services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    volumes:
      - ./:/var/www/html
      - ./storage:/var/www/html/storage
      - ./logs:/var/www/html/storage/logs
    container_name: laravel_app
    working_dir: /var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db


  webserver:
    image: nginx:alpine
    container_name: week_4_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    container_name: week_4_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: week_4
      POSTGRES_USER: permin
      POSTGRES_PASSWORD: 4488
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
